### ISSUE TITLE
RadioHead Official Repo ?

### ISSUE THREAD

**Issue by hallard** [Yveaux/RadioHead#1]
Hi Yveau,
Sorry not really an Issue, just wanted to ask you a question.
I'm currently porting RadioHead library to Spark and Photon (done and works) and ESP8266 targets and I'm wondering if this fork will be official ? IE will you be maintaining the new release of Mike on this repo ?
I'm asking this because I'm using it for long time and needed to do some changes on it mainly to be compatible with dev environment of Particle but also to some needs.
But each time Mike release a new version I need to check each file to find out the modified lines (changelog does not mention file and line modified) and it's really a pain. So having an official github could be great because it's easy so see what changed ;-)
Anyway if this will become official and updated I will do a fork
Thanks for you help

**Comment by laris** [comment]
I guess no.
but Yveau keep update the official code into this git.
it's appreciated.

**Comment by hallard** [comment]
@laris 
This is true, it's really appreciated.
I would like to do a fork and to know if @Yveaux will be open to merge some Pull Request (mainly adding ESP8266 compatibility) or not ?

**Comment by Yveaux** [comment]
@hallard Rather not, as I merely copy the original Radiohead zip-distributions to be able to have version history.
I'd suggest to write Mike your improvements and he'll most likely include them in the next release.
