### ISSUE TITLE
rf95_server compiling for Simatic IOT2020

### ISSUE THREAD

**Issue by Causticpain** [Yveaux/RadioHead#4]
Hello,

I'm trying to compile the rf95_server example for a Simatic IOT2020 (which is basically a intel Galileo Gen2), but during the compiling I get these issuses:
```

In file included from C:\Users\hladik\Documents\Arduino\libraries\RadioHead/RHGenericDriver.h:9:0,

                 from C:\Users\hladik\Documents\Arduino\libraries\RadioHead/RHSPIDriver.h:9,

                 from C:\Users\hladik\Documents\Arduino\libraries\RadioHead/RH_RF95.h:15,

                 from C:\Users\hladik\Documents\Arduino\libraries\RadioHead\examples\rf95\rf95_client\rf95_client.pde:12:

C:\Users\hladik\Documents\Arduino\libraries\RadioHead/RadioHead.h:893:27: fatal error: util/atomic.h: No such file or directory

compilation terminated.
```
atomic.h is already there in the util folder.
I'm using the Arduino IDE version 1.8.2. 
Compiling and uploading on a Arduino Mega 2560 is working fine.

Could somebody help me with this?

**Comment by Yveaux** [comment]
Sorry, this repository is only a mirror + history. See here  http://www.airspayce.com/mikem/arduino/RadioHead for the official version.
