### ISSUE TITLE
E32 TTL 1W Stops

### ISSUE THREAD

**Issue by Allecsxx** [Yveaux/RadioHead#9]
Hi

I uploaded server and client sketches to UNO and NANO. It is sending and receiving Hello world etc. All works ok, but after arround 15 seconds it stops sending for arround 3 seconds and starts again. 

Is this something to do with "512 continuously bytes from datasheet?"

What exactly means... it will send after 58 bytes, another 512 bytes and after that needs a TEA Break? Or is something i m doing wrong?

Thanks in advance

**Comment by Yveaux** [comment]
This repo is only a clone of the original that can be found at http://www.airspayce.com/mikem/arduino/RadioHead/
Please ask your question there.
